[package]
name = "sky-blog"
version = "0.1.0"
description = "Sky-Blog Desktop Application"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.6", features = ["custom-protocol", "shell-open"] }

[features]
# default custom-protocol enables custom protocol for production builds
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
